# This file is a template, and might need editing before it works on your project.
# use docker image with latex preinstalled
# since there is no official latex image, use https://github.com/blang/latex-docker
# possible alternative: https://github.com/natlownes/docker-latex
image: blang/latex

stages:
    - build

compile_documentation:
    stage: build
    script:
        - make
    artifacts:
        paths:
            - "imta_documentation.pdf"
